apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cf-issuer
resources:
  - ./helm/repository.yaml
  - ./resources/namespace.yaml
  - ./resources/release.yaml
  - ./resources/cluster-origin-issuer.yaml
  - ./secrets/issuer.yaml
