- name: Home
  columns:
    - size: small
      widgets:
        - type: clock
          hour-format: 12h
          timezones:
            - timezone: America/New_York
              label: New York
            - timezone: America/Los_Angeles
              label: San Francisco
            - timezone: Europe/London
              label: London

        - type: calendar
          first-day-of-week: monday

    - size: full
      widgets:
        - type: search
          search-engine: google
          bangs:
            - title: YouTube
              shortcut: "!yt"
              url: https://www.youtube.com/results?search_query={QUERY}
            - title: Github
              shortcut: "!gh"
              url: https://github.com/search?q={QUERY}&type=code
            - title: Grep
              shortcut: "!grep"
              url: https://grep.app/search?q={QUERY}
        - type: videos
          channels:
            - UCMwGHR0BTZuLsmjY_NT5Pwg # @ninomaeinanis
            - UCcHHkJ98eSfa5aj0mdTwwLQ # @mintfantome
        - type: group
          widgets:
            - type: hacker-news

    - size: small
      widgets:
        - type: weather
          location: ${WEATHER_LOCATION}
          units: imperial
          hour-format: 12h

        - type: bookmarks
          groups:
            - links:
                - title: Twitter
                  url: https://x.com/
                - title: Gmail
                  url: https://gmail.com/
                - title: Github
                  url: https://github.com/
                - title: YouTube
                  url: https://youtube.com/