apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flagger
  namespace: flagger
  annotations:
    cert-manager.io/cluster-issuer: stepca-issuer
spec:
  rules:
    - host: flagger.on.lu.mi
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flagger
                port:
                  number: 80
  tls:
    - hosts:
        - flagger.on.lu.mi
      secretName: cert-flagger-ingress
