apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
configurations:
  - kustomizeconfig.yaml
resources:
  - ./helm/repository.yaml
  - ./resources/namespace.yaml
  - ./resources/grafana-release.yaml
  - ./resources/grafana-ingress.yaml
  - ./resources/loki-release.yaml
  - ./resources/loki-role.yaml
configMapGenerator:
  - name: grafana-config
    files:
      - values.yaml=./config/grafana-values.yaml
  - name: loki-config
    files:
      - values.yaml=./config/loki-values.yaml
