apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./helm/repository.yaml
  - ./resources/namespace.yaml
  - ./resources/grafana-release.yaml
  - ./resources/grafana-ingress.yaml
