apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: 1password
  namespace: op-connect
spec:
  url: https://1password.github.io/connect-helm-charts/
  interval: 1h
  timeout: 5m
