apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glance
resources:
  - ./resources/namespace.yaml
  - ./resources/deployment.yaml
  - ./resources/service.yaml
  - ./resources/ingress.yaml
configMapGenerator:
  - name: glance-config
    files:
    - ./config/glance.yml
    - ./config/home.yml