apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flagger
resources:
  - ./helm/repository.yaml
  - ./resources/namespace.yaml
  - ./resources/release.yaml
  - ./resources/service.yaml
  - ./resources/ingress.yaml
